// Code generated by "stringer -type=ActivityType -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActivityTypeAll-0]
	_ = x[ActivityTypeUserViewed-1]
	_ = x[ActivityTypeUserConfirmed-2]
	_ = x[ActivityTypeUserConfirmedCustom-3]
	_ = x[ActivityTypeUserCleared-4]
	_ = x[ActivityTypeUserSkipped-5]
	_ = x[ActivityTypeUserRechecked-6]
	_ = x[ActivityTypeUserTrainingUpvote-7]
	_ = x[ActivityTypeUserTrainingDownvote-8]
	_ = x[ActivityTypeGroupViewed-9]
	_ = x[ActivityTypeGroupConfirmed-10]
	_ = x[ActivityTypeGroupConfirmedCustom-11]
	_ = x[ActivityTypeGroupCleared-12]
	_ = x[ActivityTypeGroupSkipped-13]
	_ = x[ActivityTypeGroupTrainingUpvote-14]
	_ = x[ActivityTypeGroupTrainingDownvote-15]
}

const _ActivityType_name = "ALLUSER_VIEWEDUSER_CONFIRMEDUSER_CONFIRMED_CUSTOMUSER_CLEAREDUSER_SKIPPEDUSER_RECHECKEDUSER_TRAINING_UPVOTEUSER_TRAINING_DOWNVOTEGROUP_VIEWEDGROUP_CONFIRMEDGROUP_CONFIRMED_CUSTOMGROUP_CLEAREDGROUP_SKIPPEDGROUP_TRAINING_UPVOTEGROUP_TRAINING_DOWNVOTE"

var _ActivityType_index = [...]uint8{0, 3, 14, 28, 49, 61, 73, 87, 107, 129, 141, 156, 178, 191, 204, 225, 248}

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityType_index)-1) {
		return "ActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActivityType_name[_ActivityType_index[i]:_ActivityType_index[i+1]]
}
