// Code generated by "enumer -type=ActivityType -trimprefix=ActivityType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ActivityTypeName = "AllUserViewedUserLookupUserConfirmedUserClearedUserSkippedUserQueuedRemoved1Removed2UserDeletedGroupViewedGroupLookupGroupConfirmedGroupConfirmedCustomGroupClearedGroupSkippedRemoved3Removed4GroupDeletedUserLookupDiscordAppealSubmittedAppealClaimedAppealAcceptedAppealRejectedAppealClosedAppealReopenedUserDataDeletedUserBlacklistedDiscordUserBannedDiscordUserUnbannedBotSettingUpdatedGuildBansGroupQueued"

var _ActivityTypeIndex = [...]uint16{0, 3, 13, 23, 36, 47, 58, 68, 76, 84, 95, 106, 117, 131, 151, 163, 175, 183, 191, 203, 220, 235, 248, 262, 276, 288, 302, 317, 332, 349, 368, 385, 394, 405}

const _ActivityTypeLowerName = "alluservieweduserlookupuserconfirmedusercleareduserskippeduserqueuedremoved1removed2userdeletedgroupviewedgrouplookupgroupconfirmedgroupconfirmedcustomgroupclearedgroupskippedremoved3removed4groupdeleteduserlookupdiscordappealsubmittedappealclaimedappealacceptedappealrejectedappealclosedappealreopeneduserdatadeleteduserblacklisteddiscorduserbanneddiscorduserunbannedbotsettingupdatedguildbansgroupqueued"

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityTypeIndex)-1) {
		return fmt.Sprintf("ActivityType(%d)", i)
	}
	return _ActivityTypeName[_ActivityTypeIndex[i]:_ActivityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActivityTypeNoOp() {
	var x [1]struct{}
	_ = x[ActivityTypeAll-(0)]
	_ = x[ActivityTypeUserViewed-(1)]
	_ = x[ActivityTypeUserLookup-(2)]
	_ = x[ActivityTypeUserConfirmed-(3)]
	_ = x[ActivityTypeUserCleared-(4)]
	_ = x[ActivityTypeUserSkipped-(5)]
	_ = x[ActivityTypeUserQueued-(6)]
	_ = x[ActivityTypeRemoved1-(7)]
	_ = x[ActivityTypeRemoved2-(8)]
	_ = x[ActivityTypeUserDeleted-(9)]
	_ = x[ActivityTypeGroupViewed-(10)]
	_ = x[ActivityTypeGroupLookup-(11)]
	_ = x[ActivityTypeGroupConfirmed-(12)]
	_ = x[ActivityTypeGroupConfirmedCustom-(13)]
	_ = x[ActivityTypeGroupCleared-(14)]
	_ = x[ActivityTypeGroupSkipped-(15)]
	_ = x[ActivityTypeRemoved3-(16)]
	_ = x[ActivityTypeRemoved4-(17)]
	_ = x[ActivityTypeGroupDeleted-(18)]
	_ = x[ActivityTypeUserLookupDiscord-(19)]
	_ = x[ActivityTypeAppealSubmitted-(20)]
	_ = x[ActivityTypeAppealClaimed-(21)]
	_ = x[ActivityTypeAppealAccepted-(22)]
	_ = x[ActivityTypeAppealRejected-(23)]
	_ = x[ActivityTypeAppealClosed-(24)]
	_ = x[ActivityTypeAppealReopened-(25)]
	_ = x[ActivityTypeUserDataDeleted-(26)]
	_ = x[ActivityTypeUserBlacklisted-(27)]
	_ = x[ActivityTypeDiscordUserBanned-(28)]
	_ = x[ActivityTypeDiscordUserUnbanned-(29)]
	_ = x[ActivityTypeBotSettingUpdated-(30)]
	_ = x[ActivityTypeGuildBans-(31)]
	_ = x[ActivityTypeGroupQueued-(32)]
}

var _ActivityTypeValues = []ActivityType{ActivityTypeAll, ActivityTypeUserViewed, ActivityTypeUserLookup, ActivityTypeUserConfirmed, ActivityTypeUserCleared, ActivityTypeUserSkipped, ActivityTypeUserQueued, ActivityTypeRemoved1, ActivityTypeRemoved2, ActivityTypeUserDeleted, ActivityTypeGroupViewed, ActivityTypeGroupLookup, ActivityTypeGroupConfirmed, ActivityTypeGroupConfirmedCustom, ActivityTypeGroupCleared, ActivityTypeGroupSkipped, ActivityTypeRemoved3, ActivityTypeRemoved4, ActivityTypeGroupDeleted, ActivityTypeUserLookupDiscord, ActivityTypeAppealSubmitted, ActivityTypeAppealClaimed, ActivityTypeAppealAccepted, ActivityTypeAppealRejected, ActivityTypeAppealClosed, ActivityTypeAppealReopened, ActivityTypeUserDataDeleted, ActivityTypeUserBlacklisted, ActivityTypeDiscordUserBanned, ActivityTypeDiscordUserUnbanned, ActivityTypeBotSettingUpdated, ActivityTypeGuildBans, ActivityTypeGroupQueued}

var _ActivityTypeNameToValueMap = map[string]ActivityType{
	_ActivityTypeName[0:3]:          ActivityTypeAll,
	_ActivityTypeLowerName[0:3]:     ActivityTypeAll,
	_ActivityTypeName[3:13]:         ActivityTypeUserViewed,
	_ActivityTypeLowerName[3:13]:    ActivityTypeUserViewed,
	_ActivityTypeName[13:23]:        ActivityTypeUserLookup,
	_ActivityTypeLowerName[13:23]:   ActivityTypeUserLookup,
	_ActivityTypeName[23:36]:        ActivityTypeUserConfirmed,
	_ActivityTypeLowerName[23:36]:   ActivityTypeUserConfirmed,
	_ActivityTypeName[36:47]:        ActivityTypeUserCleared,
	_ActivityTypeLowerName[36:47]:   ActivityTypeUserCleared,
	_ActivityTypeName[47:58]:        ActivityTypeUserSkipped,
	_ActivityTypeLowerName[47:58]:   ActivityTypeUserSkipped,
	_ActivityTypeName[58:68]:        ActivityTypeUserQueued,
	_ActivityTypeLowerName[58:68]:   ActivityTypeUserQueued,
	_ActivityTypeName[68:76]:        ActivityTypeRemoved1,
	_ActivityTypeLowerName[68:76]:   ActivityTypeRemoved1,
	_ActivityTypeName[76:84]:        ActivityTypeRemoved2,
	_ActivityTypeLowerName[76:84]:   ActivityTypeRemoved2,
	_ActivityTypeName[84:95]:        ActivityTypeUserDeleted,
	_ActivityTypeLowerName[84:95]:   ActivityTypeUserDeleted,
	_ActivityTypeName[95:106]:       ActivityTypeGroupViewed,
	_ActivityTypeLowerName[95:106]:  ActivityTypeGroupViewed,
	_ActivityTypeName[106:117]:      ActivityTypeGroupLookup,
	_ActivityTypeLowerName[106:117]: ActivityTypeGroupLookup,
	_ActivityTypeName[117:131]:      ActivityTypeGroupConfirmed,
	_ActivityTypeLowerName[117:131]: ActivityTypeGroupConfirmed,
	_ActivityTypeName[131:151]:      ActivityTypeGroupConfirmedCustom,
	_ActivityTypeLowerName[131:151]: ActivityTypeGroupConfirmedCustom,
	_ActivityTypeName[151:163]:      ActivityTypeGroupCleared,
	_ActivityTypeLowerName[151:163]: ActivityTypeGroupCleared,
	_ActivityTypeName[163:175]:      ActivityTypeGroupSkipped,
	_ActivityTypeLowerName[163:175]: ActivityTypeGroupSkipped,
	_ActivityTypeName[175:183]:      ActivityTypeRemoved3,
	_ActivityTypeLowerName[175:183]: ActivityTypeRemoved3,
	_ActivityTypeName[183:191]:      ActivityTypeRemoved4,
	_ActivityTypeLowerName[183:191]: ActivityTypeRemoved4,
	_ActivityTypeName[191:203]:      ActivityTypeGroupDeleted,
	_ActivityTypeLowerName[191:203]: ActivityTypeGroupDeleted,
	_ActivityTypeName[203:220]:      ActivityTypeUserLookupDiscord,
	_ActivityTypeLowerName[203:220]: ActivityTypeUserLookupDiscord,
	_ActivityTypeName[220:235]:      ActivityTypeAppealSubmitted,
	_ActivityTypeLowerName[220:235]: ActivityTypeAppealSubmitted,
	_ActivityTypeName[235:248]:      ActivityTypeAppealClaimed,
	_ActivityTypeLowerName[235:248]: ActivityTypeAppealClaimed,
	_ActivityTypeName[248:262]:      ActivityTypeAppealAccepted,
	_ActivityTypeLowerName[248:262]: ActivityTypeAppealAccepted,
	_ActivityTypeName[262:276]:      ActivityTypeAppealRejected,
	_ActivityTypeLowerName[262:276]: ActivityTypeAppealRejected,
	_ActivityTypeName[276:288]:      ActivityTypeAppealClosed,
	_ActivityTypeLowerName[276:288]: ActivityTypeAppealClosed,
	_ActivityTypeName[288:302]:      ActivityTypeAppealReopened,
	_ActivityTypeLowerName[288:302]: ActivityTypeAppealReopened,
	_ActivityTypeName[302:317]:      ActivityTypeUserDataDeleted,
	_ActivityTypeLowerName[302:317]: ActivityTypeUserDataDeleted,
	_ActivityTypeName[317:332]:      ActivityTypeUserBlacklisted,
	_ActivityTypeLowerName[317:332]: ActivityTypeUserBlacklisted,
	_ActivityTypeName[332:349]:      ActivityTypeDiscordUserBanned,
	_ActivityTypeLowerName[332:349]: ActivityTypeDiscordUserBanned,
	_ActivityTypeName[349:368]:      ActivityTypeDiscordUserUnbanned,
	_ActivityTypeLowerName[349:368]: ActivityTypeDiscordUserUnbanned,
	_ActivityTypeName[368:385]:      ActivityTypeBotSettingUpdated,
	_ActivityTypeLowerName[368:385]: ActivityTypeBotSettingUpdated,
	_ActivityTypeName[385:394]:      ActivityTypeGuildBans,
	_ActivityTypeLowerName[385:394]: ActivityTypeGuildBans,
	_ActivityTypeName[394:405]:      ActivityTypeGroupQueued,
	_ActivityTypeLowerName[394:405]: ActivityTypeGroupQueued,
}

var _ActivityTypeNames = []string{
	_ActivityTypeName[0:3],
	_ActivityTypeName[3:13],
	_ActivityTypeName[13:23],
	_ActivityTypeName[23:36],
	_ActivityTypeName[36:47],
	_ActivityTypeName[47:58],
	_ActivityTypeName[58:68],
	_ActivityTypeName[68:76],
	_ActivityTypeName[76:84],
	_ActivityTypeName[84:95],
	_ActivityTypeName[95:106],
	_ActivityTypeName[106:117],
	_ActivityTypeName[117:131],
	_ActivityTypeName[131:151],
	_ActivityTypeName[151:163],
	_ActivityTypeName[163:175],
	_ActivityTypeName[175:183],
	_ActivityTypeName[183:191],
	_ActivityTypeName[191:203],
	_ActivityTypeName[203:220],
	_ActivityTypeName[220:235],
	_ActivityTypeName[235:248],
	_ActivityTypeName[248:262],
	_ActivityTypeName[262:276],
	_ActivityTypeName[276:288],
	_ActivityTypeName[288:302],
	_ActivityTypeName[302:317],
	_ActivityTypeName[317:332],
	_ActivityTypeName[332:349],
	_ActivityTypeName[349:368],
	_ActivityTypeName[368:385],
	_ActivityTypeName[385:394],
	_ActivityTypeName[394:405],
}

// ActivityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActivityTypeString(s string) (ActivityType, error) {
	if val, ok := _ActivityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActivityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActivityType values", s)
}

// ActivityTypeValues returns all values of the enum
func ActivityTypeValues() []ActivityType {
	return _ActivityTypeValues
}

// ActivityTypeStrings returns a slice of all String values of the enum
func ActivityTypeStrings() []string {
	strs := make([]string, len(_ActivityTypeNames))
	copy(strs, _ActivityTypeNames)
	return strs
}

// IsAActivityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActivityType) IsAActivityType() bool {
	for _, v := range _ActivityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
