// Code generated by "enumer -type=ActivityType -trimprefix=ActivityType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ActivityTypeName = "AllUserViewedUserLookupUserConfirmedUserClearedUserSkippedUserQueuedRemoved1Removed2UserDeletedGroupViewedGroupLookupGroupConfirmedGroupConfirmedCustomGroupMixedGroupSkippedRemoved3Removed4GroupDeletedUserLookupDiscordAppealSubmittedAppealClaimedAppealAcceptedAppealRejectedAppealClosedAppealReopenedUserDataDeletedUserBlacklistedDiscordUserBannedDiscordUserUnbannedBotSettingUpdatedGuildBansGroupQueued"

var _ActivityTypeIndex = [...]uint16{0, 3, 13, 23, 36, 47, 58, 68, 76, 84, 95, 106, 117, 131, 151, 161, 173, 181, 189, 201, 218, 233, 246, 260, 274, 286, 300, 315, 330, 347, 366, 383, 392, 403}

const _ActivityTypeLowerName = "alluservieweduserlookupuserconfirmedusercleareduserskippeduserqueuedremoved1removed2userdeletedgroupviewedgrouplookupgroupconfirmedgroupconfirmedcustomgroupmixedgroupskippedremoved3removed4groupdeleteduserlookupdiscordappealsubmittedappealclaimedappealacceptedappealrejectedappealclosedappealreopeneduserdatadeleteduserblacklisteddiscorduserbanneddiscorduserunbannedbotsettingupdatedguildbansgroupqueued"

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityTypeIndex)-1) {
		return fmt.Sprintf("ActivityType(%d)", i)
	}
	return _ActivityTypeName[_ActivityTypeIndex[i]:_ActivityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActivityTypeNoOp() {
	var x [1]struct{}
	_ = x[ActivityTypeAll-(0)]
	_ = x[ActivityTypeUserViewed-(1)]
	_ = x[ActivityTypeUserLookup-(2)]
	_ = x[ActivityTypeUserConfirmed-(3)]
	_ = x[ActivityTypeUserCleared-(4)]
	_ = x[ActivityTypeUserSkipped-(5)]
	_ = x[ActivityTypeUserQueued-(6)]
	_ = x[ActivityTypeRemoved1-(7)]
	_ = x[ActivityTypeRemoved2-(8)]
	_ = x[ActivityTypeUserDeleted-(9)]
	_ = x[ActivityTypeGroupViewed-(10)]
	_ = x[ActivityTypeGroupLookup-(11)]
	_ = x[ActivityTypeGroupConfirmed-(12)]
	_ = x[ActivityTypeGroupConfirmedCustom-(13)]
	_ = x[ActivityTypeGroupMixed-(14)]
	_ = x[ActivityTypeGroupSkipped-(15)]
	_ = x[ActivityTypeRemoved3-(16)]
	_ = x[ActivityTypeRemoved4-(17)]
	_ = x[ActivityTypeGroupDeleted-(18)]
	_ = x[ActivityTypeUserLookupDiscord-(19)]
	_ = x[ActivityTypeAppealSubmitted-(20)]
	_ = x[ActivityTypeAppealClaimed-(21)]
	_ = x[ActivityTypeAppealAccepted-(22)]
	_ = x[ActivityTypeAppealRejected-(23)]
	_ = x[ActivityTypeAppealClosed-(24)]
	_ = x[ActivityTypeAppealReopened-(25)]
	_ = x[ActivityTypeUserDataDeleted-(26)]
	_ = x[ActivityTypeUserBlacklisted-(27)]
	_ = x[ActivityTypeDiscordUserBanned-(28)]
	_ = x[ActivityTypeDiscordUserUnbanned-(29)]
	_ = x[ActivityTypeBotSettingUpdated-(30)]
	_ = x[ActivityTypeGuildBans-(31)]
	_ = x[ActivityTypeGroupQueued-(32)]
}

var _ActivityTypeValues = []ActivityType{ActivityTypeAll, ActivityTypeUserViewed, ActivityTypeUserLookup, ActivityTypeUserConfirmed, ActivityTypeUserCleared, ActivityTypeUserSkipped, ActivityTypeUserQueued, ActivityTypeRemoved1, ActivityTypeRemoved2, ActivityTypeUserDeleted, ActivityTypeGroupViewed, ActivityTypeGroupLookup, ActivityTypeGroupConfirmed, ActivityTypeGroupConfirmedCustom, ActivityTypeGroupMixed, ActivityTypeGroupSkipped, ActivityTypeRemoved3, ActivityTypeRemoved4, ActivityTypeGroupDeleted, ActivityTypeUserLookupDiscord, ActivityTypeAppealSubmitted, ActivityTypeAppealClaimed, ActivityTypeAppealAccepted, ActivityTypeAppealRejected, ActivityTypeAppealClosed, ActivityTypeAppealReopened, ActivityTypeUserDataDeleted, ActivityTypeUserBlacklisted, ActivityTypeDiscordUserBanned, ActivityTypeDiscordUserUnbanned, ActivityTypeBotSettingUpdated, ActivityTypeGuildBans, ActivityTypeGroupQueued}

var _ActivityTypeNameToValueMap = map[string]ActivityType{
	_ActivityTypeName[0:3]:          ActivityTypeAll,
	_ActivityTypeLowerName[0:3]:     ActivityTypeAll,
	_ActivityTypeName[3:13]:         ActivityTypeUserViewed,
	_ActivityTypeLowerName[3:13]:    ActivityTypeUserViewed,
	_ActivityTypeName[13:23]:        ActivityTypeUserLookup,
	_ActivityTypeLowerName[13:23]:   ActivityTypeUserLookup,
	_ActivityTypeName[23:36]:        ActivityTypeUserConfirmed,
	_ActivityTypeLowerName[23:36]:   ActivityTypeUserConfirmed,
	_ActivityTypeName[36:47]:        ActivityTypeUserCleared,
	_ActivityTypeLowerName[36:47]:   ActivityTypeUserCleared,
	_ActivityTypeName[47:58]:        ActivityTypeUserSkipped,
	_ActivityTypeLowerName[47:58]:   ActivityTypeUserSkipped,
	_ActivityTypeName[58:68]:        ActivityTypeUserQueued,
	_ActivityTypeLowerName[58:68]:   ActivityTypeUserQueued,
	_ActivityTypeName[68:76]:        ActivityTypeRemoved1,
	_ActivityTypeLowerName[68:76]:   ActivityTypeRemoved1,
	_ActivityTypeName[76:84]:        ActivityTypeRemoved2,
	_ActivityTypeLowerName[76:84]:   ActivityTypeRemoved2,
	_ActivityTypeName[84:95]:        ActivityTypeUserDeleted,
	_ActivityTypeLowerName[84:95]:   ActivityTypeUserDeleted,
	_ActivityTypeName[95:106]:       ActivityTypeGroupViewed,
	_ActivityTypeLowerName[95:106]:  ActivityTypeGroupViewed,
	_ActivityTypeName[106:117]:      ActivityTypeGroupLookup,
	_ActivityTypeLowerName[106:117]: ActivityTypeGroupLookup,
	_ActivityTypeName[117:131]:      ActivityTypeGroupConfirmed,
	_ActivityTypeLowerName[117:131]: ActivityTypeGroupConfirmed,
	_ActivityTypeName[131:151]:      ActivityTypeGroupConfirmedCustom,
	_ActivityTypeLowerName[131:151]: ActivityTypeGroupConfirmedCustom,
	_ActivityTypeName[151:161]:      ActivityTypeGroupMixed,
	_ActivityTypeLowerName[151:161]: ActivityTypeGroupMixed,
	_ActivityTypeName[161:173]:      ActivityTypeGroupSkipped,
	_ActivityTypeLowerName[161:173]: ActivityTypeGroupSkipped,
	_ActivityTypeName[173:181]:      ActivityTypeRemoved3,
	_ActivityTypeLowerName[173:181]: ActivityTypeRemoved3,
	_ActivityTypeName[181:189]:      ActivityTypeRemoved4,
	_ActivityTypeLowerName[181:189]: ActivityTypeRemoved4,
	_ActivityTypeName[189:201]:      ActivityTypeGroupDeleted,
	_ActivityTypeLowerName[189:201]: ActivityTypeGroupDeleted,
	_ActivityTypeName[201:218]:      ActivityTypeUserLookupDiscord,
	_ActivityTypeLowerName[201:218]: ActivityTypeUserLookupDiscord,
	_ActivityTypeName[218:233]:      ActivityTypeAppealSubmitted,
	_ActivityTypeLowerName[218:233]: ActivityTypeAppealSubmitted,
	_ActivityTypeName[233:246]:      ActivityTypeAppealClaimed,
	_ActivityTypeLowerName[233:246]: ActivityTypeAppealClaimed,
	_ActivityTypeName[246:260]:      ActivityTypeAppealAccepted,
	_ActivityTypeLowerName[246:260]: ActivityTypeAppealAccepted,
	_ActivityTypeName[260:274]:      ActivityTypeAppealRejected,
	_ActivityTypeLowerName[260:274]: ActivityTypeAppealRejected,
	_ActivityTypeName[274:286]:      ActivityTypeAppealClosed,
	_ActivityTypeLowerName[274:286]: ActivityTypeAppealClosed,
	_ActivityTypeName[286:300]:      ActivityTypeAppealReopened,
	_ActivityTypeLowerName[286:300]: ActivityTypeAppealReopened,
	_ActivityTypeName[300:315]:      ActivityTypeUserDataDeleted,
	_ActivityTypeLowerName[300:315]: ActivityTypeUserDataDeleted,
	_ActivityTypeName[315:330]:      ActivityTypeUserBlacklisted,
	_ActivityTypeLowerName[315:330]: ActivityTypeUserBlacklisted,
	_ActivityTypeName[330:347]:      ActivityTypeDiscordUserBanned,
	_ActivityTypeLowerName[330:347]: ActivityTypeDiscordUserBanned,
	_ActivityTypeName[347:366]:      ActivityTypeDiscordUserUnbanned,
	_ActivityTypeLowerName[347:366]: ActivityTypeDiscordUserUnbanned,
	_ActivityTypeName[366:383]:      ActivityTypeBotSettingUpdated,
	_ActivityTypeLowerName[366:383]: ActivityTypeBotSettingUpdated,
	_ActivityTypeName[383:392]:      ActivityTypeGuildBans,
	_ActivityTypeLowerName[383:392]: ActivityTypeGuildBans,
	_ActivityTypeName[392:403]:      ActivityTypeGroupQueued,
	_ActivityTypeLowerName[392:403]: ActivityTypeGroupQueued,
}

var _ActivityTypeNames = []string{
	_ActivityTypeName[0:3],
	_ActivityTypeName[3:13],
	_ActivityTypeName[13:23],
	_ActivityTypeName[23:36],
	_ActivityTypeName[36:47],
	_ActivityTypeName[47:58],
	_ActivityTypeName[58:68],
	_ActivityTypeName[68:76],
	_ActivityTypeName[76:84],
	_ActivityTypeName[84:95],
	_ActivityTypeName[95:106],
	_ActivityTypeName[106:117],
	_ActivityTypeName[117:131],
	_ActivityTypeName[131:151],
	_ActivityTypeName[151:161],
	_ActivityTypeName[161:173],
	_ActivityTypeName[173:181],
	_ActivityTypeName[181:189],
	_ActivityTypeName[189:201],
	_ActivityTypeName[201:218],
	_ActivityTypeName[218:233],
	_ActivityTypeName[233:246],
	_ActivityTypeName[246:260],
	_ActivityTypeName[260:274],
	_ActivityTypeName[274:286],
	_ActivityTypeName[286:300],
	_ActivityTypeName[300:315],
	_ActivityTypeName[315:330],
	_ActivityTypeName[330:347],
	_ActivityTypeName[347:366],
	_ActivityTypeName[366:383],
	_ActivityTypeName[383:392],
	_ActivityTypeName[392:403],
}

// ActivityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActivityTypeString(s string) (ActivityType, error) {
	if val, ok := _ActivityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActivityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActivityType values", s)
}

// ActivityTypeValues returns all values of the enum
func ActivityTypeValues() []ActivityType {
	return _ActivityTypeValues
}

// ActivityTypeStrings returns a slice of all String values of the enum
func ActivityTypeStrings() []string {
	strs := make([]string, len(_ActivityTypeNames))
	copy(strs, _ActivityTypeNames)
	return strs
}

// IsAActivityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActivityType) IsAActivityType() bool {
	for _, v := range _ActivityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
