// Code generated by "enumer -type=ChatModel -trimprefix=ChatModel -linecomment"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ChatModelName = "gemini-2.0-flashgpt-4o-miniqwq-32Bdeepseek-r1-distill-qwen-32bdeepseek-r1-distill-llama-70Bllama-3.3-70B-instruct"

var _ChatModelIndex = [...]uint8{0, 16, 27, 34, 62, 91, 113}

const _ChatModelLowerName = "gemini-2.0-flashgpt-4o-miniqwq-32bdeepseek-r1-distill-qwen-32bdeepseek-r1-distill-llama-70bllama-3.3-70b-instruct"

func (i ChatModel) String() string {
	if i < 0 || i >= ChatModel(len(_ChatModelIndex)-1) {
		return fmt.Sprintf("ChatModel(%d)", i)
	}
	return _ChatModelName[_ChatModelIndex[i]:_ChatModelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChatModelNoOp() {
	var x [1]struct{}
	_ = x[ChatModelGemini2_0Flash-(0)]
	_ = x[ChatModelGPT4oMini-(1)]
	_ = x[ChatModelQwQ32B-(2)]
	_ = x[ChatModelDeepseekQwen32B-(3)]
	_ = x[ChatModelDeepseekR1-(4)]
	_ = x[ChatModelLlama3_3_70B-(5)]
}

var _ChatModelValues = []ChatModel{ChatModelGemini2_0Flash, ChatModelGPT4oMini, ChatModelQwQ32B, ChatModelDeepseekQwen32B, ChatModelDeepseekR1, ChatModelLlama3_3_70B}

var _ChatModelNameToValueMap = map[string]ChatModel{
	_ChatModelName[0:16]:        ChatModelGemini2_0Flash,
	_ChatModelLowerName[0:16]:   ChatModelGemini2_0Flash,
	_ChatModelName[16:27]:       ChatModelGPT4oMini,
	_ChatModelLowerName[16:27]:  ChatModelGPT4oMini,
	_ChatModelName[27:34]:       ChatModelQwQ32B,
	_ChatModelLowerName[27:34]:  ChatModelQwQ32B,
	_ChatModelName[34:62]:       ChatModelDeepseekQwen32B,
	_ChatModelLowerName[34:62]:  ChatModelDeepseekQwen32B,
	_ChatModelName[62:91]:       ChatModelDeepseekR1,
	_ChatModelLowerName[62:91]:  ChatModelDeepseekR1,
	_ChatModelName[91:113]:      ChatModelLlama3_3_70B,
	_ChatModelLowerName[91:113]: ChatModelLlama3_3_70B,
}

var _ChatModelNames = []string{
	_ChatModelName[0:16],
	_ChatModelName[16:27],
	_ChatModelName[27:34],
	_ChatModelName[34:62],
	_ChatModelName[62:91],
	_ChatModelName[91:113],
}

// ChatModelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChatModelString(s string) (ChatModel, error) {
	if val, ok := _ChatModelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChatModelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChatModel values", s)
}

// ChatModelValues returns all values of the enum
func ChatModelValues() []ChatModel {
	return _ChatModelValues
}

// ChatModelStrings returns a slice of all String values of the enum
func ChatModelStrings() []string {
	strs := make([]string, len(_ChatModelNames))
	copy(strs, _ChatModelNames)
	return strs
}

// IsAChatModel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChatModel) IsAChatModel() bool {
	for _, v := range _ChatModelValues {
		if i == v {
			return true
		}
	}
	return false
}
