// Code generated by "enumer -type=GroupType -trimprefix=GroupType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _GroupTypeName = "MixedFlaggedConfirmed"

var _GroupTypeIndex = [...]uint8{0, 5, 12, 21}

const _GroupTypeLowerName = "mixedflaggedconfirmed"

func (i GroupType) String() string {
	if i < 0 || i >= GroupType(len(_GroupTypeIndex)-1) {
		return fmt.Sprintf("GroupType(%d)", i)
	}
	return _GroupTypeName[_GroupTypeIndex[i]:_GroupTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GroupTypeNoOp() {
	var x [1]struct{}
	_ = x[GroupTypeMixed-(0)]
	_ = x[GroupTypeFlagged-(1)]
	_ = x[GroupTypeConfirmed-(2)]
}

var _GroupTypeValues = []GroupType{GroupTypeMixed, GroupTypeFlagged, GroupTypeConfirmed}

var _GroupTypeNameToValueMap = map[string]GroupType{
	_GroupTypeName[0:5]:        GroupTypeMixed,
	_GroupTypeLowerName[0:5]:   GroupTypeMixed,
	_GroupTypeName[5:12]:       GroupTypeFlagged,
	_GroupTypeLowerName[5:12]:  GroupTypeFlagged,
	_GroupTypeName[12:21]:      GroupTypeConfirmed,
	_GroupTypeLowerName[12:21]: GroupTypeConfirmed,
}

var _GroupTypeNames = []string{
	_GroupTypeName[0:5],
	_GroupTypeName[5:12],
	_GroupTypeName[12:21],
}

// GroupTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GroupTypeString(s string) (GroupType, error) {
	if val, ok := _GroupTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GroupTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GroupType values", s)
}

// GroupTypeValues returns all values of the enum
func GroupTypeValues() []GroupType {
	return _GroupTypeValues
}

// GroupTypeStrings returns a slice of all String values of the enum
func GroupTypeStrings() []string {
	strs := make([]string, len(_GroupTypeNames))
	copy(strs, _GroupTypeNames)
	return strs
}

// IsAGroupType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GroupType) IsAGroupType() bool {
	for _, v := range _GroupTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
