// Code generated by "enumer -type=GroupReasonType -trimprefix=GroupReasonType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _GroupReasonTypeName = "MemberPurposeDescriptionShout"

var _GroupReasonTypeIndex = [...]uint8{0, 6, 13, 24, 29}

const _GroupReasonTypeLowerName = "memberpurposedescriptionshout"

func (i GroupReasonType) String() string {
	if i < 0 || i >= GroupReasonType(len(_GroupReasonTypeIndex)-1) {
		return fmt.Sprintf("GroupReasonType(%d)", i)
	}
	return _GroupReasonTypeName[_GroupReasonTypeIndex[i]:_GroupReasonTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GroupReasonTypeNoOp() {
	var x [1]struct{}
	_ = x[GroupReasonTypeMember-(0)]
	_ = x[GroupReasonTypePurpose-(1)]
	_ = x[GroupReasonTypeDescription-(2)]
	_ = x[GroupReasonTypeShout-(3)]
}

var _GroupReasonTypeValues = []GroupReasonType{GroupReasonTypeMember, GroupReasonTypePurpose, GroupReasonTypeDescription, GroupReasonTypeShout}

var _GroupReasonTypeNameToValueMap = map[string]GroupReasonType{
	_GroupReasonTypeName[0:6]:        GroupReasonTypeMember,
	_GroupReasonTypeLowerName[0:6]:   GroupReasonTypeMember,
	_GroupReasonTypeName[6:13]:       GroupReasonTypePurpose,
	_GroupReasonTypeLowerName[6:13]:  GroupReasonTypePurpose,
	_GroupReasonTypeName[13:24]:      GroupReasonTypeDescription,
	_GroupReasonTypeLowerName[13:24]: GroupReasonTypeDescription,
	_GroupReasonTypeName[24:29]:      GroupReasonTypeShout,
	_GroupReasonTypeLowerName[24:29]: GroupReasonTypeShout,
}

var _GroupReasonTypeNames = []string{
	_GroupReasonTypeName[0:6],
	_GroupReasonTypeName[6:13],
	_GroupReasonTypeName[13:24],
	_GroupReasonTypeName[24:29],
}

// GroupReasonTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GroupReasonTypeString(s string) (GroupReasonType, error) {
	if val, ok := _GroupReasonTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GroupReasonTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GroupReasonType values", s)
}

// GroupReasonTypeValues returns all values of the enum
func GroupReasonTypeValues() []GroupReasonType {
	return _GroupReasonTypeValues
}

// GroupReasonTypeStrings returns a slice of all String values of the enum
func GroupReasonTypeStrings() []string {
	strs := make([]string, len(_GroupReasonTypeNames))
	copy(strs, _GroupReasonTypeNames)
	return strs
}

// IsAGroupReasonType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GroupReasonType) IsAGroupReasonType() bool {
	for _, v := range _GroupReasonTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
