// Code generated by "enumer -type=ReviewerStatsPeriod -trimprefix=ReviewerStatsPeriod"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ReviewerStatsPeriodName = "DailyWeeklyMonthly"

var _ReviewerStatsPeriodIndex = [...]uint8{0, 5, 11, 18}

const _ReviewerStatsPeriodLowerName = "dailyweeklymonthly"

func (i ReviewerStatsPeriod) String() string {
	if i < 0 || i >= ReviewerStatsPeriod(len(_ReviewerStatsPeriodIndex)-1) {
		return fmt.Sprintf("ReviewerStatsPeriod(%d)", i)
	}
	return _ReviewerStatsPeriodName[_ReviewerStatsPeriodIndex[i]:_ReviewerStatsPeriodIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReviewerStatsPeriodNoOp() {
	var x [1]struct{}
	_ = x[ReviewerStatsPeriodDaily-(0)]
	_ = x[ReviewerStatsPeriodWeekly-(1)]
	_ = x[ReviewerStatsPeriodMonthly-(2)]
}

var _ReviewerStatsPeriodValues = []ReviewerStatsPeriod{ReviewerStatsPeriodDaily, ReviewerStatsPeriodWeekly, ReviewerStatsPeriodMonthly}

var _ReviewerStatsPeriodNameToValueMap = map[string]ReviewerStatsPeriod{
	_ReviewerStatsPeriodName[0:5]:        ReviewerStatsPeriodDaily,
	_ReviewerStatsPeriodLowerName[0:5]:   ReviewerStatsPeriodDaily,
	_ReviewerStatsPeriodName[5:11]:       ReviewerStatsPeriodWeekly,
	_ReviewerStatsPeriodLowerName[5:11]:  ReviewerStatsPeriodWeekly,
	_ReviewerStatsPeriodName[11:18]:      ReviewerStatsPeriodMonthly,
	_ReviewerStatsPeriodLowerName[11:18]: ReviewerStatsPeriodMonthly,
}

var _ReviewerStatsPeriodNames = []string{
	_ReviewerStatsPeriodName[0:5],
	_ReviewerStatsPeriodName[5:11],
	_ReviewerStatsPeriodName[11:18],
}

// ReviewerStatsPeriodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReviewerStatsPeriodString(s string) (ReviewerStatsPeriod, error) {
	if val, ok := _ReviewerStatsPeriodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReviewerStatsPeriodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReviewerStatsPeriod values", s)
}

// ReviewerStatsPeriodValues returns all values of the enum
func ReviewerStatsPeriodValues() []ReviewerStatsPeriod {
	return _ReviewerStatsPeriodValues
}

// ReviewerStatsPeriodStrings returns a slice of all String values of the enum
func ReviewerStatsPeriodStrings() []string {
	strs := make([]string, len(_ReviewerStatsPeriodNames))
	copy(strs, _ReviewerStatsPeriodNames)
	return strs
}

// IsAReviewerStatsPeriod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReviewerStatsPeriod) IsAReviewerStatsPeriod() bool {
	for _, v := range _ReviewerStatsPeriodValues {
		if i == v {
			return true
		}
	}
	return false
}
