// Code generated by "enumer -type=UserType -trimprefix=UserType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _UserTypeName = "ClearedFlaggedConfirmedQueuedBloxDBMixedPastOffender"

var _UserTypeIndex = [...]uint8{0, 7, 14, 23, 29, 35, 40, 52}

const _UserTypeLowerName = "clearedflaggedconfirmedqueuedbloxdbmixedpastoffender"

func (i UserType) String() string {
	if i < 0 || i >= UserType(len(_UserTypeIndex)-1) {
		return fmt.Sprintf("UserType(%d)", i)
	}
	return _UserTypeName[_UserTypeIndex[i]:_UserTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserTypeNoOp() {
	var x [1]struct{}
	_ = x[UserTypeCleared-(0)]
	_ = x[UserTypeFlagged-(1)]
	_ = x[UserTypeConfirmed-(2)]
	_ = x[UserTypeQueued-(3)]
	_ = x[UserTypeBloxDB-(4)]
	_ = x[UserTypeMixed-(5)]
	_ = x[UserTypePastOffender-(6)]
}

var _UserTypeValues = []UserType{UserTypeCleared, UserTypeFlagged, UserTypeConfirmed, UserTypeQueued, UserTypeBloxDB, UserTypeMixed, UserTypePastOffender}

var _UserTypeNameToValueMap = map[string]UserType{
	_UserTypeName[0:7]:        UserTypeCleared,
	_UserTypeLowerName[0:7]:   UserTypeCleared,
	_UserTypeName[7:14]:       UserTypeFlagged,
	_UserTypeLowerName[7:14]:  UserTypeFlagged,
	_UserTypeName[14:23]:      UserTypeConfirmed,
	_UserTypeLowerName[14:23]: UserTypeConfirmed,
	_UserTypeName[23:29]:      UserTypeQueued,
	_UserTypeLowerName[23:29]: UserTypeQueued,
	_UserTypeName[29:35]:      UserTypeBloxDB,
	_UserTypeLowerName[29:35]: UserTypeBloxDB,
	_UserTypeName[35:40]:      UserTypeMixed,
	_UserTypeLowerName[35:40]: UserTypeMixed,
	_UserTypeName[40:52]:      UserTypePastOffender,
	_UserTypeLowerName[40:52]: UserTypePastOffender,
}

var _UserTypeNames = []string{
	_UserTypeName[0:7],
	_UserTypeName[7:14],
	_UserTypeName[14:23],
	_UserTypeName[23:29],
	_UserTypeName[29:35],
	_UserTypeName[35:40],
	_UserTypeName[40:52],
}

// UserTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserTypeString(s string) (UserType, error) {
	if val, ok := _UserTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserType values", s)
}

// UserTypeValues returns all values of the enum
func UserTypeValues() []UserType {
	return _UserTypeValues
}

// UserTypeStrings returns a slice of all String values of the enum
func UserTypeStrings() []string {
	strs := make([]string, len(_UserTypeNames))
	copy(strs, _UserTypeNames)
	return strs
}

// IsAUserType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserType) IsAUserType() bool {
	for _, v := range _UserTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
