// Code generated by "enumer -type=UserType -trimprefix=UserType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _UserTypeName = "ConfirmedFlaggedCleared"

var _UserTypeIndex = [...]uint8{0, 9, 16, 23}

const _UserTypeLowerName = "confirmedflaggedcleared"

func (i UserType) String() string {
	if i < 0 || i >= UserType(len(_UserTypeIndex)-1) {
		return fmt.Sprintf("UserType(%d)", i)
	}
	return _UserTypeName[_UserTypeIndex[i]:_UserTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserTypeNoOp() {
	var x [1]struct{}
	_ = x[UserTypeConfirmed-(0)]
	_ = x[UserTypeFlagged-(1)]
	_ = x[UserTypeCleared-(2)]
}

var _UserTypeValues = []UserType{UserTypeConfirmed, UserTypeFlagged, UserTypeCleared}

var _UserTypeNameToValueMap = map[string]UserType{
	_UserTypeName[0:9]:        UserTypeConfirmed,
	_UserTypeLowerName[0:9]:   UserTypeConfirmed,
	_UserTypeName[9:16]:       UserTypeFlagged,
	_UserTypeLowerName[9:16]:  UserTypeFlagged,
	_UserTypeName[16:23]:      UserTypeCleared,
	_UserTypeLowerName[16:23]: UserTypeCleared,
}

var _UserTypeNames = []string{
	_UserTypeName[0:9],
	_UserTypeName[9:16],
	_UserTypeName[16:23],
}

// UserTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserTypeString(s string) (UserType, error) {
	if val, ok := _UserTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserType values", s)
}

// UserTypeValues returns all values of the enum
func UserTypeValues() []UserType {
	return _UserTypeValues
}

// UserTypeStrings returns a slice of all String values of the enum
func UserTypeStrings() []string {
	strs := make([]string, len(_UserTypeNames))
	copy(strs, _UserTypeNames)
	return strs
}

// IsAUserType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserType) IsAUserType() bool {
	for _, v := range _UserTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
