version: "2"
run:
  go: "1.24"
  relative-path-mode: gomod
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - iface
    - ireturn
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl
    - interfacebloat
    - gocognit
    - noinlineerr
    - lll
  settings:
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - ^net/url.URL$
        - ^os/exec.Cmd$
        - ^reflect.StructField$
        - ^github.com/Shopify/sarama.Config$
        - ^github.com/Shopify/sarama.ProducerMessage$
        - ^github.com/mitchellh/mapstructure.DecoderConfig$
        - ^github.com/prometheus/client_golang/.+Opts$
        - ^github.com/spf13/cobra.Command$
        - ^github.com/spf13/cobra.CompletionOptions$
        - ^github.com/stretchr/testify/mock.Mock$
        - ^github.com/testcontainers/testcontainers-go.+Request$
        - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
        - ^golang.org/x/tools/go/analysis.Analyzer$
        - ^google.golang.org/protobuf/.+Options$
        - ^gopkg.in/yaml.v3.Node$
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 160
      statements: 70
      ignore-comments: true
    gochecksumtype:
      default-signifies-exhaustive: false
    goconst:
      min-len: 4
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - singleCaseSwitch
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - fieldalignment
        - errorsas
      enable-all: true
    inamedparam:
      skip-single-param: true
    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    reassign:
      patterns:
        - .*
    usetesting:
      os-temp-dir: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - staticcheck
        path: internal/database/service
        text: 'SA1019: .* is deprecated: Use Service\(\)\..*\(\) instead\.'
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
      - linters:
          - containedctx
        path: internal/tui/
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/database/migrations/
issues:
  max-same-issues: 50
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
