// Code generated by "stringer -type=ActivityType -linecomment"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActivityTypeAll-0]
	_ = x[ActivityTypeViewed-1]
	_ = x[ActivityTypeBanned-2]
	_ = x[ActivityTypeBannedCustom-3]
	_ = x[ActivityTypeCleared-4]
	_ = x[ActivityTypeSkipped-5]
	_ = x[ActivityTypeRechecked-6]
}

const _ActivityType_name = "ALLVIEWEDBANNEDBANNED_CUSTOMCLEAREDSKIPPEDRECHECKED"

var _ActivityType_index = [...]uint8{0, 3, 9, 15, 28, 35, 42, 51}

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityType_index)-1) {
		return "ActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActivityType_name[_ActivityType_index[i]:_ActivityType_index[i+1]]
}
