// Code generated by "enumer -type=ActivityType -trimprefix=ActivityType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ActivityTypeName = "AllUserViewedUserLookupUserReasonUpdatedUserConfirmedUserClearedUserSkippedUserRecheckedUserTrainingUpvoteUserTrainingDownvoteUserDeletedGroupViewedGroupLookupGroupReasonUpdatedGroupConfirmedGroupConfirmedCustomGroupClearedGroupSkippedGroupTrainingUpvoteGroupTrainingDownvoteGroupDeletedUserLookupDiscordAppealSubmittedAppealClaimedAppealAcceptedAppealRejectedAppealClosedAppealReopenedUserDataDeletedDiscordUserBannedDiscordUserUnbannedBotSettingUpdatedGuildBans"

var _ActivityTypeIndex = [...]uint16{0, 3, 13, 23, 40, 53, 64, 75, 88, 106, 126, 137, 148, 159, 177, 191, 211, 223, 235, 254, 275, 287, 304, 319, 332, 346, 360, 372, 386, 401, 418, 437, 454, 463}

const _ActivityTypeLowerName = "alluservieweduserlookupuserreasonupdateduserconfirmedusercleareduserskippeduserrecheckedusertrainingupvoteusertrainingdownvoteuserdeletedgroupviewedgrouplookupgroupreasonupdatedgroupconfirmedgroupconfirmedcustomgroupclearedgroupskippedgrouptrainingupvotegrouptrainingdownvotegroupdeleteduserlookupdiscordappealsubmittedappealclaimedappealacceptedappealrejectedappealclosedappealreopeneduserdatadeleteddiscorduserbanneddiscorduserunbannedbotsettingupdatedguildbans"

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityTypeIndex)-1) {
		return fmt.Sprintf("ActivityType(%d)", i)
	}
	return _ActivityTypeName[_ActivityTypeIndex[i]:_ActivityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActivityTypeNoOp() {
	var x [1]struct{}
	_ = x[ActivityTypeAll-(0)]
	_ = x[ActivityTypeUserViewed-(1)]
	_ = x[ActivityTypeUserLookup-(2)]
	_ = x[ActivityTypeUserReasonUpdated-(3)]
	_ = x[ActivityTypeUserConfirmed-(4)]
	_ = x[ActivityTypeUserCleared-(5)]
	_ = x[ActivityTypeUserSkipped-(6)]
	_ = x[ActivityTypeUserRechecked-(7)]
	_ = x[ActivityTypeUserTrainingUpvote-(8)]
	_ = x[ActivityTypeUserTrainingDownvote-(9)]
	_ = x[ActivityTypeUserDeleted-(10)]
	_ = x[ActivityTypeGroupViewed-(11)]
	_ = x[ActivityTypeGroupLookup-(12)]
	_ = x[ActivityTypeGroupReasonUpdated-(13)]
	_ = x[ActivityTypeGroupConfirmed-(14)]
	_ = x[ActivityTypeGroupConfirmedCustom-(15)]
	_ = x[ActivityTypeGroupCleared-(16)]
	_ = x[ActivityTypeGroupSkipped-(17)]
	_ = x[ActivityTypeGroupTrainingUpvote-(18)]
	_ = x[ActivityTypeGroupTrainingDownvote-(19)]
	_ = x[ActivityTypeGroupDeleted-(20)]
	_ = x[ActivityTypeUserLookupDiscord-(21)]
	_ = x[ActivityTypeAppealSubmitted-(22)]
	_ = x[ActivityTypeAppealClaimed-(23)]
	_ = x[ActivityTypeAppealAccepted-(24)]
	_ = x[ActivityTypeAppealRejected-(25)]
	_ = x[ActivityTypeAppealClosed-(26)]
	_ = x[ActivityTypeAppealReopened-(27)]
	_ = x[ActivityTypeUserDataDeleted-(28)]
	_ = x[ActivityTypeDiscordUserBanned-(29)]
	_ = x[ActivityTypeDiscordUserUnbanned-(30)]
	_ = x[ActivityTypeBotSettingUpdated-(31)]
	_ = x[ActivityTypeGuildBans-(32)]
}

var _ActivityTypeValues = []ActivityType{ActivityTypeAll, ActivityTypeUserViewed, ActivityTypeUserLookup, ActivityTypeUserReasonUpdated, ActivityTypeUserConfirmed, ActivityTypeUserCleared, ActivityTypeUserSkipped, ActivityTypeUserRechecked, ActivityTypeUserTrainingUpvote, ActivityTypeUserTrainingDownvote, ActivityTypeUserDeleted, ActivityTypeGroupViewed, ActivityTypeGroupLookup, ActivityTypeGroupReasonUpdated, ActivityTypeGroupConfirmed, ActivityTypeGroupConfirmedCustom, ActivityTypeGroupCleared, ActivityTypeGroupSkipped, ActivityTypeGroupTrainingUpvote, ActivityTypeGroupTrainingDownvote, ActivityTypeGroupDeleted, ActivityTypeUserLookupDiscord, ActivityTypeAppealSubmitted, ActivityTypeAppealClaimed, ActivityTypeAppealAccepted, ActivityTypeAppealRejected, ActivityTypeAppealClosed, ActivityTypeAppealReopened, ActivityTypeUserDataDeleted, ActivityTypeDiscordUserBanned, ActivityTypeDiscordUserUnbanned, ActivityTypeBotSettingUpdated, ActivityTypeGuildBans}

var _ActivityTypeNameToValueMap = map[string]ActivityType{
	_ActivityTypeName[0:3]:          ActivityTypeAll,
	_ActivityTypeLowerName[0:3]:     ActivityTypeAll,
	_ActivityTypeName[3:13]:         ActivityTypeUserViewed,
	_ActivityTypeLowerName[3:13]:    ActivityTypeUserViewed,
	_ActivityTypeName[13:23]:        ActivityTypeUserLookup,
	_ActivityTypeLowerName[13:23]:   ActivityTypeUserLookup,
	_ActivityTypeName[23:40]:        ActivityTypeUserReasonUpdated,
	_ActivityTypeLowerName[23:40]:   ActivityTypeUserReasonUpdated,
	_ActivityTypeName[40:53]:        ActivityTypeUserConfirmed,
	_ActivityTypeLowerName[40:53]:   ActivityTypeUserConfirmed,
	_ActivityTypeName[53:64]:        ActivityTypeUserCleared,
	_ActivityTypeLowerName[53:64]:   ActivityTypeUserCleared,
	_ActivityTypeName[64:75]:        ActivityTypeUserSkipped,
	_ActivityTypeLowerName[64:75]:   ActivityTypeUserSkipped,
	_ActivityTypeName[75:88]:        ActivityTypeUserRechecked,
	_ActivityTypeLowerName[75:88]:   ActivityTypeUserRechecked,
	_ActivityTypeName[88:106]:       ActivityTypeUserTrainingUpvote,
	_ActivityTypeLowerName[88:106]:  ActivityTypeUserTrainingUpvote,
	_ActivityTypeName[106:126]:      ActivityTypeUserTrainingDownvote,
	_ActivityTypeLowerName[106:126]: ActivityTypeUserTrainingDownvote,
	_ActivityTypeName[126:137]:      ActivityTypeUserDeleted,
	_ActivityTypeLowerName[126:137]: ActivityTypeUserDeleted,
	_ActivityTypeName[137:148]:      ActivityTypeGroupViewed,
	_ActivityTypeLowerName[137:148]: ActivityTypeGroupViewed,
	_ActivityTypeName[148:159]:      ActivityTypeGroupLookup,
	_ActivityTypeLowerName[148:159]: ActivityTypeGroupLookup,
	_ActivityTypeName[159:177]:      ActivityTypeGroupReasonUpdated,
	_ActivityTypeLowerName[159:177]: ActivityTypeGroupReasonUpdated,
	_ActivityTypeName[177:191]:      ActivityTypeGroupConfirmed,
	_ActivityTypeLowerName[177:191]: ActivityTypeGroupConfirmed,
	_ActivityTypeName[191:211]:      ActivityTypeGroupConfirmedCustom,
	_ActivityTypeLowerName[191:211]: ActivityTypeGroupConfirmedCustom,
	_ActivityTypeName[211:223]:      ActivityTypeGroupCleared,
	_ActivityTypeLowerName[211:223]: ActivityTypeGroupCleared,
	_ActivityTypeName[223:235]:      ActivityTypeGroupSkipped,
	_ActivityTypeLowerName[223:235]: ActivityTypeGroupSkipped,
	_ActivityTypeName[235:254]:      ActivityTypeGroupTrainingUpvote,
	_ActivityTypeLowerName[235:254]: ActivityTypeGroupTrainingUpvote,
	_ActivityTypeName[254:275]:      ActivityTypeGroupTrainingDownvote,
	_ActivityTypeLowerName[254:275]: ActivityTypeGroupTrainingDownvote,
	_ActivityTypeName[275:287]:      ActivityTypeGroupDeleted,
	_ActivityTypeLowerName[275:287]: ActivityTypeGroupDeleted,
	_ActivityTypeName[287:304]:      ActivityTypeUserLookupDiscord,
	_ActivityTypeLowerName[287:304]: ActivityTypeUserLookupDiscord,
	_ActivityTypeName[304:319]:      ActivityTypeAppealSubmitted,
	_ActivityTypeLowerName[304:319]: ActivityTypeAppealSubmitted,
	_ActivityTypeName[319:332]:      ActivityTypeAppealClaimed,
	_ActivityTypeLowerName[319:332]: ActivityTypeAppealClaimed,
	_ActivityTypeName[332:346]:      ActivityTypeAppealAccepted,
	_ActivityTypeLowerName[332:346]: ActivityTypeAppealAccepted,
	_ActivityTypeName[346:360]:      ActivityTypeAppealRejected,
	_ActivityTypeLowerName[346:360]: ActivityTypeAppealRejected,
	_ActivityTypeName[360:372]:      ActivityTypeAppealClosed,
	_ActivityTypeLowerName[360:372]: ActivityTypeAppealClosed,
	_ActivityTypeName[372:386]:      ActivityTypeAppealReopened,
	_ActivityTypeLowerName[372:386]: ActivityTypeAppealReopened,
	_ActivityTypeName[386:401]:      ActivityTypeUserDataDeleted,
	_ActivityTypeLowerName[386:401]: ActivityTypeUserDataDeleted,
	_ActivityTypeName[401:418]:      ActivityTypeDiscordUserBanned,
	_ActivityTypeLowerName[401:418]: ActivityTypeDiscordUserBanned,
	_ActivityTypeName[418:437]:      ActivityTypeDiscordUserUnbanned,
	_ActivityTypeLowerName[418:437]: ActivityTypeDiscordUserUnbanned,
	_ActivityTypeName[437:454]:      ActivityTypeBotSettingUpdated,
	_ActivityTypeLowerName[437:454]: ActivityTypeBotSettingUpdated,
	_ActivityTypeName[454:463]:      ActivityTypeGuildBans,
	_ActivityTypeLowerName[454:463]: ActivityTypeGuildBans,
}

var _ActivityTypeNames = []string{
	_ActivityTypeName[0:3],
	_ActivityTypeName[3:13],
	_ActivityTypeName[13:23],
	_ActivityTypeName[23:40],
	_ActivityTypeName[40:53],
	_ActivityTypeName[53:64],
	_ActivityTypeName[64:75],
	_ActivityTypeName[75:88],
	_ActivityTypeName[88:106],
	_ActivityTypeName[106:126],
	_ActivityTypeName[126:137],
	_ActivityTypeName[137:148],
	_ActivityTypeName[148:159],
	_ActivityTypeName[159:177],
	_ActivityTypeName[177:191],
	_ActivityTypeName[191:211],
	_ActivityTypeName[211:223],
	_ActivityTypeName[223:235],
	_ActivityTypeName[235:254],
	_ActivityTypeName[254:275],
	_ActivityTypeName[275:287],
	_ActivityTypeName[287:304],
	_ActivityTypeName[304:319],
	_ActivityTypeName[319:332],
	_ActivityTypeName[332:346],
	_ActivityTypeName[346:360],
	_ActivityTypeName[360:372],
	_ActivityTypeName[372:386],
	_ActivityTypeName[386:401],
	_ActivityTypeName[401:418],
	_ActivityTypeName[418:437],
	_ActivityTypeName[437:454],
	_ActivityTypeName[454:463],
}

// ActivityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActivityTypeString(s string) (ActivityType, error) {
	if val, ok := _ActivityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActivityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActivityType values", s)
}

// ActivityTypeValues returns all values of the enum
func ActivityTypeValues() []ActivityType {
	return _ActivityTypeValues
}

// ActivityTypeStrings returns a slice of all String values of the enum
func ActivityTypeStrings() []string {
	strs := make([]string, len(_ActivityTypeNames))
	copy(strs, _ActivityTypeNames)
	return strs
}

// IsAActivityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActivityType) IsAActivityType() bool {
	for _, v := range _ActivityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
