// Code generated by "enumer -type=ActivityType -trimprefix=ActivityType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ActivityTypeName = "AllUserViewedUserLookupUserConfirmedUserClearedUserSkippedUserRecheckedUserTrainingUpvoteUserTrainingDownvoteUserDeletedGroupViewedGroupLookupGroupConfirmedGroupConfirmedCustomGroupClearedGroupSkippedGroupTrainingUpvoteGroupTrainingDownvoteGroupDeletedUserLookupDiscordAppealSubmittedAppealClaimedAppealAcceptedAppealRejectedAppealClosedDiscordUserBannedDiscordUserUnbannedBotSettingUpdatedGuildBans"

var _ActivityTypeIndex = [...]uint16{0, 3, 13, 23, 36, 47, 58, 71, 89, 109, 120, 131, 142, 156, 176, 188, 200, 219, 240, 252, 269, 284, 297, 311, 325, 337, 354, 373, 390, 399}

const _ActivityTypeLowerName = "alluservieweduserlookupuserconfirmedusercleareduserskippeduserrecheckedusertrainingupvoteusertrainingdownvoteuserdeletedgroupviewedgrouplookupgroupconfirmedgroupconfirmedcustomgroupclearedgroupskippedgrouptrainingupvotegrouptrainingdownvotegroupdeleteduserlookupdiscordappealsubmittedappealclaimedappealacceptedappealrejectedappealcloseddiscorduserbanneddiscorduserunbannedbotsettingupdatedguildbans"

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityTypeIndex)-1) {
		return fmt.Sprintf("ActivityType(%d)", i)
	}
	return _ActivityTypeName[_ActivityTypeIndex[i]:_ActivityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActivityTypeNoOp() {
	var x [1]struct{}
	_ = x[ActivityTypeAll-(0)]
	_ = x[ActivityTypeUserViewed-(1)]
	_ = x[ActivityTypeUserLookup-(2)]
	_ = x[ActivityTypeUserConfirmed-(3)]
	_ = x[ActivityTypeUserCleared-(4)]
	_ = x[ActivityTypeUserSkipped-(5)]
	_ = x[ActivityTypeUserRechecked-(6)]
	_ = x[ActivityTypeUserTrainingUpvote-(7)]
	_ = x[ActivityTypeUserTrainingDownvote-(8)]
	_ = x[ActivityTypeUserDeleted-(9)]
	_ = x[ActivityTypeGroupViewed-(10)]
	_ = x[ActivityTypeGroupLookup-(11)]
	_ = x[ActivityTypeGroupConfirmed-(12)]
	_ = x[ActivityTypeGroupConfirmedCustom-(13)]
	_ = x[ActivityTypeGroupCleared-(14)]
	_ = x[ActivityTypeGroupSkipped-(15)]
	_ = x[ActivityTypeGroupTrainingUpvote-(16)]
	_ = x[ActivityTypeGroupTrainingDownvote-(17)]
	_ = x[ActivityTypeGroupDeleted-(18)]
	_ = x[ActivityTypeUserLookupDiscord-(19)]
	_ = x[ActivityTypeAppealSubmitted-(20)]
	_ = x[ActivityTypeAppealClaimed-(21)]
	_ = x[ActivityTypeAppealAccepted-(22)]
	_ = x[ActivityTypeAppealRejected-(23)]
	_ = x[ActivityTypeAppealClosed-(24)]
	_ = x[ActivityTypeDiscordUserBanned-(25)]
	_ = x[ActivityTypeDiscordUserUnbanned-(26)]
	_ = x[ActivityTypeBotSettingUpdated-(27)]
	_ = x[ActivityTypeGuildBans-(28)]
}

var _ActivityTypeValues = []ActivityType{ActivityTypeAll, ActivityTypeUserViewed, ActivityTypeUserLookup, ActivityTypeUserConfirmed, ActivityTypeUserCleared, ActivityTypeUserSkipped, ActivityTypeUserRechecked, ActivityTypeUserTrainingUpvote, ActivityTypeUserTrainingDownvote, ActivityTypeUserDeleted, ActivityTypeGroupViewed, ActivityTypeGroupLookup, ActivityTypeGroupConfirmed, ActivityTypeGroupConfirmedCustom, ActivityTypeGroupCleared, ActivityTypeGroupSkipped, ActivityTypeGroupTrainingUpvote, ActivityTypeGroupTrainingDownvote, ActivityTypeGroupDeleted, ActivityTypeUserLookupDiscord, ActivityTypeAppealSubmitted, ActivityTypeAppealClaimed, ActivityTypeAppealAccepted, ActivityTypeAppealRejected, ActivityTypeAppealClosed, ActivityTypeDiscordUserBanned, ActivityTypeDiscordUserUnbanned, ActivityTypeBotSettingUpdated, ActivityTypeGuildBans}

var _ActivityTypeNameToValueMap = map[string]ActivityType{
	_ActivityTypeName[0:3]:          ActivityTypeAll,
	_ActivityTypeLowerName[0:3]:     ActivityTypeAll,
	_ActivityTypeName[3:13]:         ActivityTypeUserViewed,
	_ActivityTypeLowerName[3:13]:    ActivityTypeUserViewed,
	_ActivityTypeName[13:23]:        ActivityTypeUserLookup,
	_ActivityTypeLowerName[13:23]:   ActivityTypeUserLookup,
	_ActivityTypeName[23:36]:        ActivityTypeUserConfirmed,
	_ActivityTypeLowerName[23:36]:   ActivityTypeUserConfirmed,
	_ActivityTypeName[36:47]:        ActivityTypeUserCleared,
	_ActivityTypeLowerName[36:47]:   ActivityTypeUserCleared,
	_ActivityTypeName[47:58]:        ActivityTypeUserSkipped,
	_ActivityTypeLowerName[47:58]:   ActivityTypeUserSkipped,
	_ActivityTypeName[58:71]:        ActivityTypeUserRechecked,
	_ActivityTypeLowerName[58:71]:   ActivityTypeUserRechecked,
	_ActivityTypeName[71:89]:        ActivityTypeUserTrainingUpvote,
	_ActivityTypeLowerName[71:89]:   ActivityTypeUserTrainingUpvote,
	_ActivityTypeName[89:109]:       ActivityTypeUserTrainingDownvote,
	_ActivityTypeLowerName[89:109]:  ActivityTypeUserTrainingDownvote,
	_ActivityTypeName[109:120]:      ActivityTypeUserDeleted,
	_ActivityTypeLowerName[109:120]: ActivityTypeUserDeleted,
	_ActivityTypeName[120:131]:      ActivityTypeGroupViewed,
	_ActivityTypeLowerName[120:131]: ActivityTypeGroupViewed,
	_ActivityTypeName[131:142]:      ActivityTypeGroupLookup,
	_ActivityTypeLowerName[131:142]: ActivityTypeGroupLookup,
	_ActivityTypeName[142:156]:      ActivityTypeGroupConfirmed,
	_ActivityTypeLowerName[142:156]: ActivityTypeGroupConfirmed,
	_ActivityTypeName[156:176]:      ActivityTypeGroupConfirmedCustom,
	_ActivityTypeLowerName[156:176]: ActivityTypeGroupConfirmedCustom,
	_ActivityTypeName[176:188]:      ActivityTypeGroupCleared,
	_ActivityTypeLowerName[176:188]: ActivityTypeGroupCleared,
	_ActivityTypeName[188:200]:      ActivityTypeGroupSkipped,
	_ActivityTypeLowerName[188:200]: ActivityTypeGroupSkipped,
	_ActivityTypeName[200:219]:      ActivityTypeGroupTrainingUpvote,
	_ActivityTypeLowerName[200:219]: ActivityTypeGroupTrainingUpvote,
	_ActivityTypeName[219:240]:      ActivityTypeGroupTrainingDownvote,
	_ActivityTypeLowerName[219:240]: ActivityTypeGroupTrainingDownvote,
	_ActivityTypeName[240:252]:      ActivityTypeGroupDeleted,
	_ActivityTypeLowerName[240:252]: ActivityTypeGroupDeleted,
	_ActivityTypeName[252:269]:      ActivityTypeUserLookupDiscord,
	_ActivityTypeLowerName[252:269]: ActivityTypeUserLookupDiscord,
	_ActivityTypeName[269:284]:      ActivityTypeAppealSubmitted,
	_ActivityTypeLowerName[269:284]: ActivityTypeAppealSubmitted,
	_ActivityTypeName[284:297]:      ActivityTypeAppealClaimed,
	_ActivityTypeLowerName[284:297]: ActivityTypeAppealClaimed,
	_ActivityTypeName[297:311]:      ActivityTypeAppealAccepted,
	_ActivityTypeLowerName[297:311]: ActivityTypeAppealAccepted,
	_ActivityTypeName[311:325]:      ActivityTypeAppealRejected,
	_ActivityTypeLowerName[311:325]: ActivityTypeAppealRejected,
	_ActivityTypeName[325:337]:      ActivityTypeAppealClosed,
	_ActivityTypeLowerName[325:337]: ActivityTypeAppealClosed,
	_ActivityTypeName[337:354]:      ActivityTypeDiscordUserBanned,
	_ActivityTypeLowerName[337:354]: ActivityTypeDiscordUserBanned,
	_ActivityTypeName[354:373]:      ActivityTypeDiscordUserUnbanned,
	_ActivityTypeLowerName[354:373]: ActivityTypeDiscordUserUnbanned,
	_ActivityTypeName[373:390]:      ActivityTypeBotSettingUpdated,
	_ActivityTypeLowerName[373:390]: ActivityTypeBotSettingUpdated,
	_ActivityTypeName[390:399]:      ActivityTypeGuildBans,
	_ActivityTypeLowerName[390:399]: ActivityTypeGuildBans,
}

var _ActivityTypeNames = []string{
	_ActivityTypeName[0:3],
	_ActivityTypeName[3:13],
	_ActivityTypeName[13:23],
	_ActivityTypeName[23:36],
	_ActivityTypeName[36:47],
	_ActivityTypeName[47:58],
	_ActivityTypeName[58:71],
	_ActivityTypeName[71:89],
	_ActivityTypeName[89:109],
	_ActivityTypeName[109:120],
	_ActivityTypeName[120:131],
	_ActivityTypeName[131:142],
	_ActivityTypeName[142:156],
	_ActivityTypeName[156:176],
	_ActivityTypeName[176:188],
	_ActivityTypeName[188:200],
	_ActivityTypeName[200:219],
	_ActivityTypeName[219:240],
	_ActivityTypeName[240:252],
	_ActivityTypeName[252:269],
	_ActivityTypeName[269:284],
	_ActivityTypeName[284:297],
	_ActivityTypeName[297:311],
	_ActivityTypeName[311:325],
	_ActivityTypeName[325:337],
	_ActivityTypeName[337:354],
	_ActivityTypeName[354:373],
	_ActivityTypeName[373:390],
	_ActivityTypeName[390:399],
}

// ActivityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActivityTypeString(s string) (ActivityType, error) {
	if val, ok := _ActivityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActivityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActivityType values", s)
}

// ActivityTypeValues returns all values of the enum
func ActivityTypeValues() []ActivityType {
	return _ActivityTypeValues
}

// ActivityTypeStrings returns a slice of all String values of the enum
func ActivityTypeStrings() []string {
	strs := make([]string, len(_ActivityTypeNames))
	copy(strs, _ActivityTypeNames)
	return strs
}

// IsAActivityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActivityType) IsAActivityType() bool {
	for _, v := range _ActivityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
