// Code generated by "enumer -type=ChatModel -trimprefix=ChatModel -linecomment"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ChatModelName = "gemini-1.5-pro-latestgemini-1.5-flash-latestgemini-1.5-flash-8b-latest"

var _ChatModelIndex = [...]uint8{0, 21, 44, 70}

const _ChatModelLowerName = "gemini-1.5-pro-latestgemini-1.5-flash-latestgemini-1.5-flash-8b-latest"

func (i ChatModel) String() string {
	if i < 0 || i >= ChatModel(len(_ChatModelIndex)-1) {
		return fmt.Sprintf("ChatModel(%d)", i)
	}
	return _ChatModelName[_ChatModelIndex[i]:_ChatModelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChatModelNoOp() {
	var x [1]struct{}
	_ = x[ChatModelGeminiPro-(0)]
	_ = x[ChatModelGeminiFlash-(1)]
	_ = x[ChatModelGeminiFlash8B-(2)]
}

var _ChatModelValues = []ChatModel{ChatModelGeminiPro, ChatModelGeminiFlash, ChatModelGeminiFlash8B}

var _ChatModelNameToValueMap = map[string]ChatModel{
	_ChatModelName[0:21]:       ChatModelGeminiPro,
	_ChatModelLowerName[0:21]:  ChatModelGeminiPro,
	_ChatModelName[21:44]:      ChatModelGeminiFlash,
	_ChatModelLowerName[21:44]: ChatModelGeminiFlash,
	_ChatModelName[44:70]:      ChatModelGeminiFlash8B,
	_ChatModelLowerName[44:70]: ChatModelGeminiFlash8B,
}

var _ChatModelNames = []string{
	_ChatModelName[0:21],
	_ChatModelName[21:44],
	_ChatModelName[44:70],
}

// ChatModelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChatModelString(s string) (ChatModel, error) {
	if val, ok := _ChatModelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChatModelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChatModel values", s)
}

// ChatModelValues returns all values of the enum
func ChatModelValues() []ChatModel {
	return _ChatModelValues
}

// ChatModelStrings returns a slice of all String values of the enum
func ChatModelStrings() []string {
	strs := make([]string, len(_ChatModelNames))
	copy(strs, _ChatModelNames)
	return strs
}

// IsAChatModel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChatModel) IsAChatModel() bool {
	for _, v := range _ChatModelValues {
		if i == v {
			return true
		}
	}
	return false
}
