// Code generated by "enumer -type=ChatModel -trimprefix=ChatModel -linecomment"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _ChatModelName = "gemini-2.0-flash-001gemini-1.5-flashgemini-1.5-flash-8b"

var _ChatModelIndex = [...]uint8{0, 20, 36, 55}

const _ChatModelLowerName = "gemini-2.0-flash-001gemini-1.5-flashgemini-1.5-flash-8b"

func (i ChatModel) String() string {
	if i < 0 || i >= ChatModel(len(_ChatModelIndex)-1) {
		return fmt.Sprintf("ChatModel(%d)", i)
	}
	return _ChatModelName[_ChatModelIndex[i]:_ChatModelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChatModelNoOp() {
	var x [1]struct{}
	_ = x[ChatModelGeminiFlash2_0-(0)]
	_ = x[ChatModelGeminiFlash1_5-(1)]
	_ = x[ChatModelGeminiFlash1_5_8B-(2)]
}

var _ChatModelValues = []ChatModel{ChatModelGeminiFlash2_0, ChatModelGeminiFlash1_5, ChatModelGeminiFlash1_5_8B}

var _ChatModelNameToValueMap = map[string]ChatModel{
	_ChatModelName[0:20]:       ChatModelGeminiFlash2_0,
	_ChatModelLowerName[0:20]:  ChatModelGeminiFlash2_0,
	_ChatModelName[20:36]:      ChatModelGeminiFlash1_5,
	_ChatModelLowerName[20:36]: ChatModelGeminiFlash1_5,
	_ChatModelName[36:55]:      ChatModelGeminiFlash1_5_8B,
	_ChatModelLowerName[36:55]: ChatModelGeminiFlash1_5_8B,
}

var _ChatModelNames = []string{
	_ChatModelName[0:20],
	_ChatModelName[20:36],
	_ChatModelName[36:55],
}

// ChatModelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChatModelString(s string) (ChatModel, error) {
	if val, ok := _ChatModelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChatModelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChatModel values", s)
}

// ChatModelValues returns all values of the enum
func ChatModelValues() []ChatModel {
	return _ChatModelValues
}

// ChatModelStrings returns a slice of all String values of the enum
func ChatModelStrings() []string {
	strs := make([]string, len(_ChatModelNames))
	copy(strs, _ChatModelNames)
	return strs
}

// IsAChatModel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChatModel) IsAChatModel() bool {
	for _, v := range _ChatModelValues {
		if i == v {
			return true
		}
	}
	return false
}
