// Code generated by "enumer -type=GroupType -trimprefix=GroupType"; DO NOT EDIT.

package enum

import (
	"fmt"
	"strings"
)

const _GroupTypeName = "ConfirmedFlaggedClearedUnflagged"

var _GroupTypeIndex = [...]uint8{0, 9, 16, 23, 32}

const _GroupTypeLowerName = "confirmedflaggedclearedunflagged"

func (i GroupType) String() string {
	if i < 0 || i >= GroupType(len(_GroupTypeIndex)-1) {
		return fmt.Sprintf("GroupType(%d)", i)
	}
	return _GroupTypeName[_GroupTypeIndex[i]:_GroupTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GroupTypeNoOp() {
	var x [1]struct{}
	_ = x[GroupTypeConfirmed-(0)]
	_ = x[GroupTypeFlagged-(1)]
	_ = x[GroupTypeCleared-(2)]
	_ = x[GroupTypeUnflagged-(3)]
}

var _GroupTypeValues = []GroupType{GroupTypeConfirmed, GroupTypeFlagged, GroupTypeCleared, GroupTypeUnflagged}

var _GroupTypeNameToValueMap = map[string]GroupType{
	_GroupTypeName[0:9]:        GroupTypeConfirmed,
	_GroupTypeLowerName[0:9]:   GroupTypeConfirmed,
	_GroupTypeName[9:16]:       GroupTypeFlagged,
	_GroupTypeLowerName[9:16]:  GroupTypeFlagged,
	_GroupTypeName[16:23]:      GroupTypeCleared,
	_GroupTypeLowerName[16:23]: GroupTypeCleared,
	_GroupTypeName[23:32]:      GroupTypeUnflagged,
	_GroupTypeLowerName[23:32]: GroupTypeUnflagged,
}

var _GroupTypeNames = []string{
	_GroupTypeName[0:9],
	_GroupTypeName[9:16],
	_GroupTypeName[16:23],
	_GroupTypeName[23:32],
}

// GroupTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GroupTypeString(s string) (GroupType, error) {
	if val, ok := _GroupTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GroupTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GroupType values", s)
}

// GroupTypeValues returns all values of the enum
func GroupTypeValues() []GroupType {
	return _GroupTypeValues
}

// GroupTypeStrings returns a slice of all String values of the enum
func GroupTypeStrings() []string {
	strs := make([]string, len(_GroupTypeNames))
	copy(strs, _GroupTypeNames)
	return strs
}

// IsAGroupType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GroupType) IsAGroupType() bool {
	for _, v := range _GroupTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
